"""add analise and otimizacao tables

Revision ID: 7e39788c286c
Revises: 
Create Date: 2026-06-05 02:44:54.266624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e39788c286c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analise',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('criterios', sa.JSON(), nullable=False),
    sa.Column('pontos_fortes', sa.JSON(), nullable=False),
    sa.Column('pontos_fracos', sa.JSON(), nullable=False),
    sa.Column('sugestoes', sa.JSON(), nullable=False),
    sa.Column('palavras_chave_faltando', sa.JSON(), nullable=False),
    sa.Column('certificados_sugeridos', sa.JSON(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=False),
    sa.Column('vaga', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otimizacao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('analise_id', sa.String(length=36), nullable=True),
    sa.Column('curriculo_original', sa.Text(), nullable=False),
    sa.Column('curriculo_otimizado', sa.Text(), nullable=False),
    sa.Column('melhorias', sa.JSON(), nullable=False),
    sa.Column('vaga', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analise_id'], ['analise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otimizacao')
    op.drop_table('analise')
    # ### end Alembic commands ###
