"""add titulo to chat_session

Revision ID: 8ed8058846bf
Revises: 97659b2087bf
Create Date: 2026-06-07 16:38:30.382687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed8058846bf'
down_revision = '97659b2087bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=100), nullable=False, server_default='Untitled'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
