"""add chat_session table

Revision ID: 97659b2087bf
Revises: 7e39788c286c
Create Date: 2026-06-06 12:54:44.011576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97659b2087bf'
down_revision = '7e39788c286c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('mensagens', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_session')
    # ### end Alembic commands ###
